app = "xplode-grafana"
primary_region = "bom"  # Use your preferred region here
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  GF_SECURITY_ADMIN_USER = "admin"
  GF_SECURITY_ADMIN_PASSWORD = "xplode"  # Change this!
  GF_AUTH_ANONYMOUS_ENABLED = "false"
  GF_SERVER_ROOT_URL = "https://xplode-grafana.fly.dev"
  GF_INSTALL_PLUGINS = "grafana-piechart-panel,grafana-worldmap-panel"

[mounts]
  source = "grafana_data"
  destination = "/var/lib/grafana"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024