# fly.toml app configuration file for mines-browser-wallet007
app = 'mines-browser-wallet007'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile.browser-wallet'

[env]
  RUST_LOG = 'warn'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

  [[services.http_checks]]
    interval = '30s'
    timeout = '2s'
    grace_period = '30s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[regions]
primary = ["bom", "iad"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  region = "bom"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  region = "iad"

[[metrics]]
  port = 9091
  path = '/metrics'
  https = false