# fly.toml app configuration file generated for xplode-prometheus on 2025-03-29T12:03:46+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xplode-prometheus'
primary_region = 'bom'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  PROMETHEUS_CONFIG_FILE = '/etc/prometheus/prometheus.yml'

[[mounts]]
  source = 'prometheus_data'
  destination = '/prometheus'

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
